language: python
python:
  - "2.7"

addons:
  apt:
    packages:
      - ca-certificates

install: "pip install Flask"

script:
  - echo "Unit tests"

after_script:
  - |
    python app.py &
    APP_PID=$!

  - |
    set -e

    wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip -O ngrok.zip
    unzip ngrok.zip

    # wget ngrok
    ./ngrok http 5000 > /dev/null &

    sleep 2

    NGROK_URL=$(curl -s localhost:4040/api/tunnels/command_line \
                | jq --raw-output .public_url)

    curl -s $TRIGGER_URL -d'{
    "environment": "my-dynamic-env",
    "synchronous": true,
    "url": "'"$NGROK_URL"'"
    }'

    pkill ngrok

  - kill $APP_PID
